### ISSUE TITLE
Logo selector needs an update

### ISSUE THREAD

**Issue by Marvin9** [saumeya/saumeya.github.io#1]
```
.nav-bar__logo img { 
  content: url(https://your-logo.png);
}
```

this selector won't work after version 2.5, can you please update it?

https://saumeya.github.io/4.custom-styles-argocd.html

**Comment by saumeya** [comment]
Thanks for opening the issue - updated to 
```
.sidebar__logo img { 
  content: url(https://your-logo.png);
}
```
